-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE CURSEFORGE PACKAGER
-- Please use the Localization App on CurseForge to update this
-- at http://wow.curseforge.com/addons/lui/localization/

local addonname, LUI = ...

local L = _G.LibStub("AceLocale-3.0"):NewLocale(addonname, "zhCN")
if not L then return end

-- Core
--@localization(locale="zhCN", format="lua_additive_table", handle-unlocalized="comment", namespace="", handle-subnamespaces="none", same-key-is-true=true)@


-- Auras
--@localization(locale="zhCN", format="lua_additive_table", handle-unlocalized="comment", namespace="Auras", handle-subnamespaces="none", same-key-is-true=true)@


-- Chat
--@localization(locale="zhCN", format="lua_additive_table", handle-unlocalized="comment", namespace="Chat", handle-subnamespaces="none", same-key-is-true=true)@


-- WorldMap
--@localization(locale="zhCN", format="lua_additive_table", handle-unlocalized="comment", namespace="WorldMap", handle-subnamespaces="none", same-key-is-true=true)@


-- UnitFrames
--@localization(locale="zhCN", format="lua_additive_table", handle-unlocalized="comment", namespace="Unitframes", handle-subnamespaces="none", same-key-is-true=true)@