-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE CURSEFORGE PACKAGER
-- Please use the Localization App on CurseForge to update this
-- at http://wow.curseforge.com/addons/lui/localization/

local addonname, LUI = ...

local L = _G.LibStub("AceLocale-3.0"):NewLocale(addonname, "zhCN")
if not L then return end

-- Core
L["Adjust the bottom inset of the background"] = "调整底部边框阴影效果的偏移量"
L["Adjust the horizontal position"] = "调整横向位置"
L["Adjust the left inset of the background"] = "调整左边边框阴影效果的偏移量"
L["Adjust the right inset of the background"] = "调整右边边框阴影效果的偏移量"
L["Adjust the size of each tile of the background texture"] = "调整采用平铺时材质的大小"
L["Adjust the thickness of the border"] = "调整边框的大小"
L["Adjust the top inset of the background"] = "调整顶部边框阴影效果的偏移量"
L["Adjust the vertical position"] = "调整纵向位置"
L["Anchor"] = "锚点"
L["Anchor Point"] = "锚点"
L["Are you sure?"] = "你确定吗？"
L["Background"] = "背景"
L["Border"] = "边框"
L["Bottom"] = "底部"
L["Bottom Left"] = "左下角"
L["Bottom Right"] = "右下角"
L["Center"] = "中央"
L["Choose a font"] = "选择字体"
L["Choose a font flag"] = "选择字体的描边"
L["Choose a fontsize"] = "选择字体的大小"
L["Choose a texture"] = "选择一个材质"
L["Choose the Size for your %s"] = "选择%s的大小"
L["Enable"] = "启用"
L["Flag"] = "描边"
L["Font"] = "字体"
L["General Settings"] = "常规设置"
L["Height"] = "高度"
L["Horizontal Position"] = "横向位置"
L["Index"] = "索引"
L["Insets"] = "内阴影"
L["Left"] = "左边"
L["Monochrome"] = "单色描边" -- Needs review
L["Name"] = "名称"
L["None"] = "无" -- Needs review
L["Outline"] = "细描边" -- Needs review
L["Please read the FAQ"] = [=[如有问题请先阅读”常见问题解答”！
要了解更多信息请浏览以下网址：
|cff8080ffhttp://www.wowlui.com|r

尽情享用吧！]=]
L["Revision: "] = "校订："
L["Right"] = "右边"
L["Row Spacing"] = "行距"
L["Scale"] = "缩放"
L["Should the background texture be tiled over the area"] = "使用平铺方式背景材质有可能会超出范围"
L["Size"] = "大小"
L["%s Options"] = "%s选项"
L["Spacing"] = "间距"
L["Texture"] = "材质"
L["The UI needs to be reloaded!"] = "用户界面需要重新载入！"
L["Thickness"] = "边框大小"
L["Thick Outline"] = "粗描边" -- Needs review
L["Tile"] = "平铺"
L["Tile Size"] = "材质大小"
L["Time"] = "时间"
L["Top"] = "顶部"
L["Top Left"] = "左上角"
L["Top Right"] = "右上角"
L["Version: "] = "版本："
L["Version %s available for download."] = "版本%s 可供下载"
L["Vertical Position"] = "纵向位置"
L["Welcome to LUI v3"] = [=[欢迎使用 |c0090ffffLUI v3|r！！
第一个也是唯一一个次世代魔兽世界用户界面。]=]
L["Width"] = "宽度"



-- Auras
L["Buffs"] = "增益"
L["Choose the amount of space between each of your %s"] = "选择%s之间的间距"
L["Choose the amount of space between each row of your %s"] = "选择%s的每一行之间的间距"
L["Choose the corner to anchor your %s to"] = "选择用于%s定位的锚点"
L["Choose the maximum number of rows for your %s"] = "选择%s的最大行数"
L["Choose the maximum number of %s for each row"] = "选择每行%s的最大数量"
L["Choose the sorting order for your %s"] = "选择%s的排列顺序"
L["Choose whether you want to consolidate your %s or not"] = "选择是否想要合并你的%s"
L["Choose whether you want to reverse the sorting order or not"] = "选择是否想要反向排序"
L["Consolidate %s"] = "合并%s"
L["Count"] = "计数"
L["Debuffs"] = "减益"
L["Duration"] = "持续时间"
L["Number of rows"] = "行数"
L["Number per row"] = "每行数量"
L["Reverse Sorting"] = "反向排序"
L["Sorting Order"] = "排序"



-- Chat
L["Adjust the height of the EditBox"] = "调整输入框的高度"
L["Battleground"] = "战场"
L["Battleground Leader"] = "战场领袖"
L["[BG]"] = "[战]"
L["[BL]"] = "[战场指挥]"
L["[BN:From]"] = true -- Needs review
L["[BN:To]"] = true -- Needs review
L["Buttons"] = "按钮"
L["Chat Background"] = "聊天框背景"
L["Color by channel"] = "按频道着色"
L["Copy chat button"] = "复制按钮"
L["[DG]"] = "[地]"
L["Disable fading"] = "禁用消褪"
L["Dungeon Guide"] = "地城手册"
L["EditBox"] = "输入框"
L["Free-floating"] = "自定义位置"
L["Free-floating (Locked)"] = "自定义位置（锁定）"
L["[G]"] = "[会]"
L["General"] = "常规"
L["[General]"] = "[综]"
L["Guild"] = "公会"
L["(|HBNplayer.-|h) whispers:"] = "(|HBNplayer.-|h) 密语:" -- Needs review
L["Hide Buttons"] = "隐藏按钮"
L["Holding shift while mouse scrolling will jump to top or bottom"] = "Shitf+上滚/下滚可以将聊天内容滚动到顶部/底部。"
L["(|Hplayer.-|h) whispers:"] = "(|Hplayer.-|h) 密语:" -- Needs review
L["[LFG]"] = "[组]"
L["Link hover tooltip"] = "链接可交互"
L["LocalDefense"] = "本地防务"
L["[LocalDefense]"] = "[防]"
L["LookingForGroup"] = "组队"
L["Minimalist tabs"] = "简约标签"
L["[O]"] = "[官]"
L["Officer"] = "官员"
L["[P]"] = "[队]"
L["Party"] = "小队"
L["[PL]"] = "[队长]"
L["[R]"] = "[团]"
L["Raid"] = "团队"
L["Raid Leader"] = "团队领袖"
L["Raid Warning"] = "团队警报"
L["Remember history"] = "记录会话"
L["Remembers the history of the EditBox across sessions"] = "记录输入框在不同频道时的会话"
L["Requires the Alt key to be held down to move the cursor"] = "按住Alt键后用方向键翻阅之前记录的聊天内容"
L["Reset position"] = "还原位置"
L["Reset the main chat dock's position"] = "将聊天框还原到默认的位置"
L["[RL]"] = "[团长]"
L["[RW]"] = "[团队警报]"
L["Scale of the copy chat button"] = "缩放复制按钮的大小"
L["Scale of the scroll to bottom button"] = "缩放滚动到底部按钮的大小"
L["Scroll to bottom button"] = "滚动到底部按钮"
L["Select where the EditBox anchors to the ChatFrame"] = "选择输入框的位置"
L["Sets the EditBox color to the color of your currently active channel"] = "用当前频道的类型颜色来着色输入框的颜色"
L["Shift mouse scrolling"] = "Shift+滚轮滚动"
L["Short channel names"] = "短频道名"
L["Show copy chat button"] = "显示复制聊天内容的按钮"
L["Show scroll to bottom button when scrolled up"] = "当向上翻看聊天内容时显示滚动到底部的按钮"
L["Show tooltip when mousing over links in chat"] = [=[鼠标指向链接时显示鼠标提示
链接：比如物品，法术，任务，成就，天赋，副本进度等等的内容]=]
L["Stop the chat from fading out over time"] = "防止聊天内容在一段时间后消失"
L["To (|HBNplayer.-|h):"] = "发送给 (|HBNplayer.-|h):" -- Needs review
L["To (|Hplayer.-|h):"] = "发送给 (|Hplayer.-|h):" -- Needs review
L["Trade"] = "交易"
L["[Trade]"] = "[交]"
L["Use abreviated channel names"] = "在聊天框里使用短频道名"
L["Use Alt key"] = "使用Alt键"
L["Use minimalist style tabs"] = "开启简约风格的聊天标签"
L["[W:From]"] = true -- Needs review
L["WorldDefense"] = "世界防务"
L["[WorldDefense]"] = "[世界防务]"
L["[W:To]"] = true -- Needs review



-- WorldMap
L["Battlegrounds"] = "战场"
L["BC Instances"] = "燃烧的远征副本"
L["BC Raids"] = "燃烧的远征团队副本"
L["Cataclysm Instances"] = "大灾变副本"
L["Cataclysm Raids"] = "大灾变团队副本"
L["Classic Instances"] = "旧世界副本"
L["Classic Raids"] = "旧世界团队副本"
L["Cursor"] = "光标"
L["Hide Completely"] = "完全隐藏"
L["Only Show Markers"] = "只显示标记"
L["Player"] = "玩家"
L["Quest Objectives"] = "任务目标"
L["Show Markers & Panels"] = "显示标记和面板"
L["Wrath Instances"] = "火焰的愤怒副本"
L["Wrath Raids"] = "火焰的愤怒团队副本"
L["Pandaria Instances"] = true -- needs review
L["Pandaria Raids"] = true -- needs review




-- UnitFrames
L["Blizzard does not support right-click focus"] = [=[暴雪不允许右键点击头像框体设置焦点
暴雪目前并没有提供合适的方式来支持右键点击自定义头像框体来直接设置焦点。]=]
L["Initiate a ready check"] = [=[发起就位确认
发起一个就位检查，询问你的团队成员，如果他们全部准备完毕就继续。]=]
L["Initiate a role check"] = [=[发起职务确认
发起一个职责检查，要求团队成员确认自己的职责。]=]
L["Type %s to Clear Focus"] = "输入%s清除焦点"
L["Type %s to Set Focus"] = "输入%s设置焦点"
