---@class LUIAddon
local LUI = select(2, ...)
local module = LUI:GetModule("Unitframes")

module.defaults.profile.pettarget = {
			Enable = true,
			Height = 24,
			Width = 130,
			Scale = 1,
			X = 0,
			Y = -160,
			Point = "CENTER",
			RelativePoint = "TOPLEFT",
			Border = {
				Aggro = false,
				Color = { r = 0, g = 0, b = 0, a = 1 },
				EdgeFile = "glow",
				EdgeSize = 5,
				Insets = { Bottom = 3, Left = 3, Right = 3, Top = 3 },
			},
			Backdrop = {
				Color = { r = 0, g = 0, b = 0, a = 1 },
				Padding = { Bottom = -4, Left = -4, Right = 4, Top = 4 },
				Texture = "Blizzard Tooltip"
			},
			HealthBar = {
				BGAlpha = 1,
				BGInvert = false,
				BGMultiplier = 0.4,
				Color = "Individual",
				Height = 24,
				IndividualColor = { r = 0.25, g = 0.25, b = 0.25 },
				Smooth = true,
				Texture = "LUI_Gradient",
				TextureBG = "LUI_Gradient",
				Width = 130,
				X = 0,
				Y = 0
			},
			PowerBar = {
				BGAlpha = 1,
				BGInvert = false,
				BGMultiplier = 0.4,
				Color = "By Class",
				Enable = false,
				Height = 10,
				IndividualColor = { r = 0.8, g = 0.8, b = 0.8 },
				Smooth = true,
				Texture = "LUI_Minimalist",
				TextureBG = "LUI_Minimalist",
				Width = 130,
				X = 0,
				Y = -26
			},
			Aura = {
				Buffs = {
					AuraTimer = false,
					ColorByType = false,
					CooldownReverse = true,
					DisableCooldown = false,
					Enable = false,
					GrowthX = "RIGHT",
					GrowthY = "UP",
					IncludePet = false,
					InitialAnchor = "TOPLEFT",
					Num = 8,
					PlayerOnly = false,
					Size = 26,
					Spacing = 2,
					X = -0.5,
					Y = 30
				},
				Debuffs = {
					AuraTimer = false,
					ColorByType = false,
					CooldownReverse = true,
					DisableCooldown = false,
					Enable = false,
					FadeOthers = false,
					GrowthX = "LEFT",
					GrowthY = "UP",
					IncludePet = false,
					InitialAnchor = "TOPRIGHT",
					Num = 36,
					PlayerOnly = false,
					Size = 26,
					Spacing = 2,
					X = -0.5,
					Y = 60
				}
			},
			Castbar = {
				Border = {
					Inset = { bottom = 3, left = 3, right = 3, top = 3 },
					Texture = "glow",
					Thickness = 4
				},
				Colors = {
					Background = { r = 0.15, g = 0.15, b = 0.15, a = 0.67 },
					Bar = { r = 0.13, g = 0.59, b = 1, a = 0.68 },
					Border = { r = 0, g = 0, b = 0, a = 0.7 },
					Name = { r = 0.9, g = 0.9, b = 0.9 },
					Shield = { r = 0.5, g = 0, b = 0, a = 0.1 },
					Time = {
						r = 0.9,
						g = 0.9,
						b = 0.9
					}
				},
				General = {
					Enable = true,
					Height = 26,
					Icon = true,
					IndividualColor = false,
					Point = "BOTTOM",
					Shield = true,
					Texture = "LUI_Gradient",
					TextureBG = "LUI_Minimalist",
					Width = 200,
					X = 0,
					Y = 70
				},
				NameText = {
					Enable = true,
					Font = "Prototype",
					OffsetX = 5,
					OffsetY = 1,
					Outline = "",
					Size = 15
				},
				Shield = {
					BarColor = { r = 0.13, g = 0.59, b = 1, a = 0.68 },
					Border = false,
					Color = { r = 0.13, g = 0.59, b = 1, a = 0.68 },
					Enable = true,
					IndividualBorder = true,
					IndividualColor = false,
					Inset = { bottom = 3, left = 3, right = 3, top = 3 },
					Text = true,
					Texture = "glow",
					Thickness = 4
				},
				TimeText = {
					Enable = true,
					Font = "Prototype",
					OffsetX = -5,
					OffsetY = 1,
					Outline = "",
					ShowMax = true,
					Size = 13
				}
			},
			Portrait = {
				Alpha = 0.5,
				Enable = false,
				Height = 43,
				Width = 90,
				X = 0,
				Y = 0
			},
			LeaderIndicator = { Enable = false, Point = "TOPLEFT", Size = 17, X = 0, Y = 0 },
			GroupRoleIndicator = { Enable = false, Point = "TOPRIGHT", Size = 22, X = 15, Y = 10 },
			PvPIndicator = { Enable = false, Point = "TOPLEFT", Size = 35, X = -12, Y = 10 },
			RaidMarkerIndicator = { Enable = true, Point = "CENTER", Size = 55, X = 0, Y = 0 },
			NameText = {
				ColorClassByClass = false,
				ColorLevelByDifficulty = false,
				ColorNameByClass = false,
				Enable = true,
				Font = "Prototype",
				Format = "Name",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Length = "Short",
				Outline = "",
				Point = "CENTER",
				RelativePoint = "CENTER",
				ShortClassification = false,
				ShowClassification = false,
				Size = 15,
				X = 0,
				Y = 0
			},
			HealthText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				Format = "Absolut Short",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "TOPRIGHT",
				RelativePoint = "BOTTOMRIGHT",
				ShowAlways = true,
				ShowDead = false,
				Size = 14,
				X = -2,
				Y = -2
			},
			PowerText = {
				Color = "By Class",
				Enable = false,
				Font = "Prototype",
				Format = "Absolut Short",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "BOTTOMLEFT",
				RelativePoint = "BOTTOMRIGHT",
				ShowEmpty = true,
				ShowFull = true,
				Size = 24,
				X = 0,
				Y = -66
			},
			HealthPercentText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "CENTER",
				RelativePoint = "CENTER",
				ShowAlways = false,
				ShowDead = true,
				Size = 24,
				X = 0,
				Y = 0
			},
			PowerPercentText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "CENTER",
				RelativePoint = "CENTER",
				ShowEmpty = false,
				ShowFull = false,
				Size = 24,
				X = 0,
				Y = 0
			},
			HealthMissingText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "RIGHT",
				RelativePoint = "RIGHT",
				ShortValue = true,
				ShowAlways = false,
				Size = 24,
				X = 0,
				Y = 0
			},
			PowerMissingText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "RIGHT",
				RelativePoint = "RIGHT",
				ShortValue = true,
				ShowEmpty = false,
				ShowFull = false,
				Size = 24,
				X = 0,
				Y = 0
			},
			Fader = {
				Casting = true,
				Combat = true,
				Enable = false,
				Health = true,
				HealthClip = 1,
				Hover = true,
				HoverAlpha = 0.75,
				InAlpha = 1,
				OutAlpha = 0.1,
				OutDelay = 0,
				OutTime = 1.5,
				Power = true,
				PowerClip = 0.9,
				Targeting = true,
				UseGlobalSettings = true
			},
		}
