---@class LUIAddon
local LUI = select(2, ...)
local module = LUI:GetModule("Unitframes")

module.defaults.profile.player = {
			Enable = true,
			Height = 43,
			Width = 250,
			Scale = 1,
			X = -200,
			Y = -200,
			Point = "CENTER",
			RelativePoint = "TOPLEFT",
			Border = {
				Aggro = false,
				Color = { r = 0, g = 0, b = 0, a = 1 },
				EdgeFile = "glow",
				EdgeSize = 5,
				Insets = { Bottom = 3, Left = 3, Right = 3, Top = 3 },
			},
			Backdrop = {
				Color = { r = 0, g = 0, b = 0, a = 1 },
				Padding = { Bottom = -4, Left = -4, Right = 4, Top = 4 },
				Texture = "Blizzard Tooltip"
			},
			HealthBar = {
				BGAlpha = 1,
				BGInvert = false,
				BGMultiplier = 0.4,
				Color = "Individual",
				Height = 30,
				IndividualColor = { r = 0.25, g = 0.25, b = 0.25 },
				Smooth = true,
				Texture = "LUI_Gradient",
				TextureBG = "LUI_Gradient",
				Width = 250,
				X = 0,
				Y = 0
			},
			PowerBar = {
				BGAlpha = 1,
				BGInvert = false,
				BGMultiplier = 0.4,
				Color = "By Class",
				Enable = true,
				Height = 10,
				IndividualColor = { r = 0.8, g = 0.8, b = 0.8 },
				Smooth = true,
				Texture = "LUI_Minimalist",
				TextureBG = "LUI_Minimalist",
				Width = 250,
				X = 0,
				Y = -32
			},
			HealthPredictionBar = {
				Enable = false,
				MyColor = { r = 0, g = 0.5, b = 0, a = 0.25 },
				OtherColor = { r = 0, g = 1, b = 0, a = 0.25 },
				Texture = "LUI_Gradient"
			},
			TotalAbsorbBar = {
				Enable = false,
				MyColor = { r = 0, g = 1, b = 0, a = 0.5 },
				Texture = "LUI_Gradient"
			},
			Aura = {
				Buffs = {
					AuraTimer = false,
					ColorByType = false,
					CooldownReverse = true,
					DisableCooldown = false,
					Enable = false,
					GrowthX = "LEFT",
					GrowthY = "DOWN",
					IncludePet = false,
					InitialAnchor = "BOTTOMRIGHT",
					Num = 8,
					PlayerOnly = false,
					Size = 26,
					Spacing = 2,
					X = -0.5,
					Y = -30
				},
				Debuffs = {
					AuraTimer = false,
					ColorByType = false,
					CooldownReverse = true,
					DisableCooldown = false,
					Enable = false,
					FadeOthers = false,
					GrowthX = "RIGHT",
					GrowthY = "DOWN",
					IncludePet = false,
					InitialAnchor = "BOTTOMLEFT",
					Num = 36,
					PlayerOnly = false,
					Size = 26,
					Spacing = 2,
					X = -0.5,
					Y = 60
				}
			},
			Castbar = {
				Border = {
					Inset = { bottom = 3, left = 3, right = 3, top = 3 },
					Texture = "glow",
					Thickness = 4
				},
				Colors = {
					Background = { r = 0.15, g = 0.15, b = 0.15, a = 0.67 },
					Bar = { r = 0.13, g = 0.59, b = 1, a = 0.68 },
					Border = { r = 0, g = 0, b = 0, a = 0.7 },
					Latency = { r = 0.11, g = 0.11, b = 0.11, a = 0.74 },
					Name = { r = 0.9, g = 0.9, b = 0.9 },
					Shield = { r = 0.5, g = 0, b = 0, a = 0.1 },
					Time = {
						r = 0.9,
						g = 0.9,
						b = 0.9
					}
				},
				General = {
					Enable = true,
					Height = 33,
					Icon = true,
					IndividualColor = false,
					Latency = true,
					Point = "BOTTOM",
					Shield = true,
					Texture = "LUI_Gradient",
					TextureBG = "LUI_Minimalist",
					Width = 360,
					X = 13,
					Y = 155
				},
				NameText = {
					Enable = true,
					Font = "Prototype",
					OffsetX = 5,
					OffsetY = 1,
					Outline = "",
					Size = 15
				},
				Shield = {
					BarColor = { r = 0.13, g = 0.59, b = 1, a = 0.68 },
					Border = false,
					Color = { r = 0.13, g = 0.59, b = 1, a = 0.68 },
					Enable = true,
					IndividualBorder = true,
					IndividualColor = false,
					Inset = { bottom = 3, left = 3, right = 3, top = 3 },
					Text = true,
					Texture = "glow",
					Thickness = 4
				},
				TimeText = {
					Enable = true,
					Font = "Prototype",
					OffsetX = -5,
					OffsetY = 1,
					Outline = "",
					ShowMax = true,
					Size = 13
				}
			},
			Portrait = {
				Alpha = 0.5,
				Enable = false,
				Height = 43,
				Width = 250,
				X = 0,
				Y = 0
			},
			LeaderIndicator = { Enable = true, Point = "TOPLEFT", Size = 17, X = 0, Y = 10 },
			GroupRoleIndicator = { Enable = true, Point = "TOPRIGHT", Size = 22, X = 15, Y = 10 },
			PvPIndicator = { Enable = false, Point = "TOPLEFT", Size = 35, X = -12, Y = 10 },
			RaidMarkerIndicator = { Enable = true, Point = "CENTER", Size = 55, X = 0, Y = 10 },
			RestingIndicator = { Enable = true, Point = "TOPLEFT", Size = 27, X = -12, Y = 13 },
			CombatIndicator = { Enable = false, Point = "BOTTOMLEFT", Size = 27, X = -15, Y = -30 },
			NameText = {
				ColorClassByClass = true,
				ColorLevelByDifficulty = true,
				ColorNameByClass = true,
				Enable = false,
				Font = "Prototype",
				Format = "Level + Name",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Length = "Medium",
				Outline = "",
				Point = "BOTTOMLEFT",
				RelativePoint = "BOTTOMRIGHT",
				ShortClassification = false,
				ShowClassification = true,
				Size = 24,
				X = 0,
				Y = 0
			},
			HealthText = {
				Color = "Individual",
				Enable = true,
				Font = "Prototype",
				Format = "Standard",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "BOTTOMRIGHT",
				RelativePoint = "BOTTOMRIGHT",
				ShowAlways = true,
				ShowDead = false,
				Size = 28,
				X = 0,
				Y = -31
			},
			PowerText = {
				Color = "By Class",
				Enable = true,
				Font = "Prototype",
				Format = "Standard",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "BOTTOMRIGHT",
				RelativePoint = "BOTTOMRIGHT",
				ShowEmpty = true,
				ShowFull = true,
				Size = 21,
				X = 0,
				Y = -52
			},
			HealthPercentText = {
				Color = "Individual",
				Enable = true,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "CENTER",
				RelativePoint = "CENTER",
				ShowAlways = false,
				ShowDead = true,
				Size = 16,
				X = 0,
				Y = 6
			},
			PowerPercentText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "CENTER",
				RelativePoint = "CENTER",
				ShowEmpty = false,
				ShowFull = false,
				Size = 14,
				X = 0,
				Y = -15
			},
			HealthMissingText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "BOTTOMRIGHT",
				RelativePoint = "BOTTOMRIGHT",
				ShortValue = true,
				ShowAlways = false,
				Size = 15,
				X = -3,
				Y = 0
			},
			PowerMissingText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Point = "RIGHT",
				RelativePoint = "RIGHT",
				ShortValue = true,
				ShowEmpty = false,
				ShowFull = false,
				Size = 13,
				X = -3,
				Y = -15
			},
			ClassPowerText = {
				Enable = true,
				Outline = "",
				Size = 10,
				X = 220,
				Y = 0
			},
			PvPText = {
				Color = { r = 1, g = 0.1, b = 0.1 },
				Enable = true,
				Font = "vibroceb",
				Outline = "",
				Size = 12,
				X = 20,
				Y = 5
			},
			CombatFeedback = {
				Enable = false,
				Font = "vibrocen",
				MaxAlpha = 0.6,
				Outline = "OUTLINE",
				Point = "CENTER",
				RelativePoint = "BOTTOM",
				ShowDamage = true,
				ShowEnergize = true,
				ShowHeal = true,
				ShowImmune = true,
				ShowOther = true,
				Size = 20,
				X = 0,
				Y = 0
			},
			Fader = {
				Casting = true,
				Combat = true,
				Enable = false,
				Health = true,
				HealthClip = 1,
				Hover = true,
				HoverAlpha = 0.75,
				InAlpha = 1,
				OutAlpha = 0.1,
				OutDelay = 0,
				OutTime = 1.5,
				Power = true,
				PowerClip = 0.9,
				Targeting = true,
				UseGlobalSettings = true
			},
			AlternativePowerBar = {
				BGAlpha = 1,
				BGMultiplier = 0.4,
				Color = "By Type",
				Enable = false,
				Height = 10,
				IndividualColor = { r = 1, g = 1, b = 1 },
				OverPower = false,
				Smooth = true,
				Texture = "LUI_Gradient",
				TextureBG = "LUI_Gradient",
				Width = 250,
				X = 0,
				Y = -44
			},
			AdditionalPowerBar = {
				BGAlpha = 1,
				BGMultiplier = 0.4,
				Color = "By Type",
				Enable = true,
				Height = 10,
				IndividualColor = { r = 1, g = 1, b = 1 },
				OverPower = true,
				Smooth = true,
				Texture = "LUI_Minimalist",
				TextureBG = "LUI_Minimalist",
				Width = 250,
				X = 0,
				Y = -44
			},
			TotemsBar = {
				Enable = true,
				Height = 10,
				IconScale = 1.5,
				Lock = true,
				Multiplier = 0.35,
				Padding = 1,
				Texture = "LUI_Gradient",
				Width = 250,
				X = 0,
				Y = 0.5
			},
			RunesBar = {
				Enable = true,
				Height = 8,
				Lock = true,
				Padding = 1,
				Texture = "LUI_Gradient",
				Width = 249,
				X = 0,
				Y = 0.5
			},
			ClassPowerBar = {
				Enable = true,
				Height = 8,
				Lock = true,
				Padding = 1,
				Texture = "LUI_Gradient",
				Width = 250,
				X = 0,
				Y = 0.5
			},
			AdditionalPowerText = {
				Enable = true,
				Font = "Prototype",
				Outline = "",
				Size = 14,
				X = 0,
				Y = 0,
				Point = "BOTTOM",
				RelativePoint = "BOTTOM",
				Format = "Standard",
				HideIfFullMana = true,
				Color = "Individual",
				IndividualColor = { r = 1, g = 1, b = 1 },
			},
			AlternativePowerText = {
				Color = "Individual",
				Enable = false,
				Font = "Prototype",
				Format = "Standard",
				IndividualColor = { r = 1, g = 1, b = 1 },
				Outline = "",
				Size = 10,
				X = 0,
				Y = 0
			}
		}
