-- ####################################################################################################################
-- ##### Setup and Locals #############################################################################################
-- ####################################################################################################################

---@type string, LUIAddon
local _, LUI = ...
local L = LUI.L

---@class ArtworkModule : LUIModule
local module = LUI:NewModule("Artwork")

-- ####################################################################################################################
-- ##### Default Settings #############################################################################################
-- ####################################################################################################################

module.defaults = {
	profile = {
		Textures = {
			["Raid Border"] = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner_border.tga",
				Point = "TOPLEFT",
				Parent = "oUF_LUI_raid",
				RelativePoint = "TOPLEFT",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 415,
				Height = 190,
				Order = 1,
				X = -12,
				Y = 11,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
			["Raid Background"] = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner.tga",
				Point = "TOPLEFT",
				Parent = "oUF_LUI_raid",
				RelativePoint = "TOPLEFT",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 415,
				Height = 190,
				Order = 1,
				X = -2,
				Y = 2,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
			["Chat Border"] = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner_border.tga",
				Point = "TOPRIGHT",
				Parent = "ChatAlphaAnchor",
				RelativePoint = "TOPRIGHT",
				CustomTexCoords = false,
				HorizontalFlip = true,
				VerticalFlip = false,
				Width = 415,
				Height = 190,
				Order = 1,
				X = 11,
				Y = 9,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
			["Chat Background"] = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner.tga",
				Point = "TOPRIGHT",
				Parent = "ChatAlphaAnchor",
				RelativePoint = "TOPRIGHT",
				CustomTexCoords = false,
				HorizontalFlip = true,
				VerticalFlip = false,
				Width = 415,
				Height = 190,
				Order = 1,
				X = 1,
				Y = 0,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
		--[[	TestBG = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner.tga",
				Point = "TOPLEFT",
				Parent = "ObjectiveTrackerFrame",
				RelativePoint = "TOPLEFT",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 409,
				Height = 182,
				Order = 2,
				X = -25,
				Y = -2,
                FrameLevel = 1,
                Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},]]
			["Top Bar"] = {
				Anchored = true,
				TexMode = 1,
				Texture = "bar_top.tga",
				Point = "BOTTOM",
				Parent = "UIParent",
				RelativePoint = "BOTTOM",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 702,
				Height = 36,
				Order = 3,
				X = 0,
				Y = 80,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
			["Bottom Bar"] = {
				Anchored = true,
				TexMode = 1,
				Texture = "bar_bottom.tga",
				Point = "BOTTOM",
				Parent = "UIParent",
				RelativePoint = "BOTTOM",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 720,
				Height = 50,
				Order = 3,
				X = 0,
				Y = -15,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
			-- ["InfoPanel BG bLeft"] = {
			-- 	Anchored = true,
			-- 	TexMode = 1,
			-- 	Texture = "left_border_back.tga",
			-- 	Point = "BOTTOMLEFT",
			-- 	Parent = "UIParent",
			-- 	RelativePoint = "BOTTOMLEFT",
			-- 	CustomTexCoords = false,
			-- 	HorizontalFlip = false,
			-- 	VerticalFlip = false,
			-- 	Width = 1024,
			-- 	Height = 1024,
			-- 	Order = 3,
			-- 	X = -23,
			-- 	Y = -23,
			-- 	FrameLevel = 1,
			-- 	Strata = "BACKGROUND",
			-- 	Left = 0,
			-- 	Right = 1,
			-- 	Up = 0,
			-- 	Down = 1,
			-- },
			-- ["InfoPanel bLeft"] = {
			-- 	Anchored = true,
			-- 	TexMode = 1,
			-- 	Texture = "left_border.tga",
			-- 	Point = "BOTTOMLEFT",
			-- 	Parent = "UIParent",
			-- 	RelativePoint = "BOTTOMLEFT",
			-- 	CustomTexCoords = false,
			-- 	HorizontalFlip = false,
			-- 	VerticalFlip = false,
			-- 	Width = 1024,
			-- 	Height = 1024,
			-- 	Order = 3,
			-- 	X = -30,
			-- 	Y = -30,
			-- 	FrameLevel = 1,
			-- 	Strata = "BACKGROUND",
			-- 	Left = 0,
			-- 	Right = 1,
			-- 	Up = 0,
			-- 	Down = 1,
			-- },
			-- ["InfoPanel BG bRight"] = {
			-- 	Anchored = true,
			-- 	TexMode = 1,
			-- 	Texture = "left_border_back.tga",
			-- 	Point = "BOTTOMRIGHT",
			-- 	Parent = "UIParent",
			-- 	RelativePoint = "BOTTOMRIGHT",
			-- 	CustomTexCoords = false,
			-- 	HorizontalFlip = true,
			-- 	VerticalFlip = false,
			-- 	Width = 1024,
			-- 	Height = 1024,
			-- 	Order = 3,
			-- 	X = 23,
			-- 	Y = -23,
			-- 	FrameLevel = 1,
			-- 	Strata = "BACKGROUND",
			-- 	Left = 0,
			-- 	Right = 1,
			-- 	Up = 0,
			-- 	Down = 1,
			-- },
			-- ["InfoPanel bRight"] = {
			-- 	Anchored = true,
			-- 	TexMode = 1,
			-- 	Texture = "left_border.tga",
			-- 	Point = "BOTTOMRIGHT",
			-- 	Parent = "UIParent",
			-- 	RelativePoint = "BOTTOMRIGHT",
			-- 	CustomTexCoords = false,
			-- 	HorizontalFlip = true,
			-- 	VerticalFlip = false,
			-- 	Width = 1024,
			-- 	Height = 1024,
			-- 	Order = 3,
			-- 	X = 30,
			-- 	Y = -30,
			-- 	FrameLevel = 1,
			-- 	Strata = "BACKGROUND",
			-- 	Left = 0,
			-- 	Right = 1,
			-- 	Up = 0,
			-- 	Down = 1,
			-- },
			-- ["Info Bar"] = {
			-- 	Anchored = true,
			-- 	TexMode = 1,
			-- 	Texture = "left_border.tga",
			-- 	Point = "BOTTOMRIGHT",
			-- 	Parent = "UIParent",
			-- 	RelativePoint = "BOTTOMRIGHT",
			-- 	CustomTexCoords = false,
			-- 	HorizontalFlip = true,
			-- 	VerticalFlip = false,
			-- 	Width = 1024,
			-- 	Height = 1024,
			-- 	Order = 3,
			-- 	X = 30,
			-- 	Y = -30,
			-- 	FrameLevel = 1,
			-- 	Strata = "BACKGROUND",
			-- 	Left = 0,
			-- 	Right = 1,
			-- 	Up = 0,
			-- 	Down = 1,
			-- },
			['*'] = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner.tga",
				Point = "CENTER",
				Parent = "UIParent",
				RelativePoint = "CENTER",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 400,
				Height = 300,
				Order = 100,
				X = 0,
				Y = 0,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Scale = 1,
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
		},
        Buttons = {
            ButtonTest = {
				Anchored = true,
				TexMode = 1,
				Texture = "panel_corner.tga",
				Point = "CENTER",
				Parent = "UIParent",
				RelativePoint = "CENTER",
				CustomTexCoords = false,
				HorizontalFlip = false,
				VerticalFlip = false,
				Width = 400,
				Height = 300,
				Order = 100,
				X = 0,
				Y = 0,
				FrameLevel = 1,
				Strata = "BACKGROUND",
				Scale = 1,
				Left = 0,
				Right = 1,
				Up = 0,
				Down = 1,
			},
        },
		Colors = {
			ChatBG = { r = 0.12, g = 0.12,  b = 0.12, a = 0.5, t = "Class", },
			["Top Bar"] = { r = 0.12, g = 0.12,  b = 0.12, a = 0.5, t = "Class", },
			['*'] = { r = 0.12, g = 0.12,  b = 0.12, a = 1, t = "Class", },
		}
	},
}
-- ####################################################################################################################
-- ##### Framework Events #############################################################################################
-- ####################################################################################################################

function module:OnInitialize()
	LUI:RegisterModule(module)
end

function module:OnEnable()
	module:setPanels()
end

function module:OnDisable()
end
